language: node_js
node_js:
- 8.10.0
services:
- mongodb
before_script: 
before_install: 
after_success: 
env:
  global:
  - secure: HMNKVIyi2jS3nxy9PcyjAlnuMoc1I9CwbXf24Dm1L1bo4xysRRY2qbN4GvGOIKkzwPefcWhQAatkV6lRLFKj6wEjDLIZtH7TyGe3CQNJtN1nzIaHW5Gj37FqodM11LNHbMi00JWTXTovpFIHDim/WRT73iFOK6XNG8UfpANQo99UhEn6yfyUyxtV0sJ6iqkzRyiYgL6FA3jhIrTzbVtBPZJYKULKY8vu47xU0qJ/1vr2O3Zga04HApr6SRm7f5vfFRLrZrUstwhHdDKsDTGgUmCCTOoHHRCMynq8maRqfAWEMpTOMLq4OgeY50H5tQlG2Xt4biBpHBT5KFA45/i2K2SMwFSXnZzIPKe/ArJ/LaVldyEB6XCymTgiXtTfMkor8AiwGymxsQLA09DxLcJFUGv5ScZiscw5gYpfT2FuTRMdjkjxfz6HAca+YpxyvWzr4YbWMKQGvAfs0L590t9z7q98+aoeWQRBlPh5ZsuX6+u0FExGRA4sQepxyWlvXP1ZTBUYGPN5jaEZF7USMGFT1YzU35iIMmoUI84Xy92LES7wwyZfrzin2xZ2n9b22N34H1lxjVFuMf1pGVST56Z7f1LuQcsTziMc35MOPXSiPlKQY3k86zlEAEPvTGJJv9U08VUMtPquPoWeL/bM2UaNT6vTQa4mvz7V5DJZ/4Ljnrc=
  - secure: oARP+BihMuAgXYLnVEb0Uo7qMrrHIn202hLyjpWUs7fwwBF+oLf7QDoJBrS2m0dXpyZNTHfU2D9Twr5PgYWkESPJOoxPyi0gadEikdBTP+fywup5NR3/c1havIFDkS52DAYtEPrgOQHN4AyRPNxhTK6DqGxs30PNPUYC7bav5pXcNg0zkrDMrV+VGkXe3Wu9c1SggeAO4SqaEQi117dHOGTLxe+wJq95vcdmT/e54ziW1W6ANPoJL0/tFDn1Lk7XFVPqfVAQeyCMV/O56hh4wRx8Z03AxaJX5xFWHcCwtfmloTNztGS7ekFiiDM0oME6UVsJXCHcgjcIlNjdnDDpD0hg6jO1dj9xvHc2xf6W21tpyl3HFhoiR+FCgup2yjwHnTWo+k348LNkkMOtXCcKjDLNaC06WKAKw+XK2XUs/XkBVdRetDuvrfYqu+bsBEipouBJ2SUdLWLAIJNJ1BDcGYBJK7pM8uuCr/Wdm807DLSvFKAaEmln1Zo7zriwJTj4h/TH+luAAQ1tJgI+c712jIVD/QVR8xVD1BsyDbu9yOE5fkbArl0d7vNvj8Q26NpXJAey7VD0tSy06RbJlvuLmvoWifL/Y8cyO9Rp4OMIjJdUM4vtBINGej6BoCR5LIr1VoH1wzKxDLGMP7lL1XWyb2BeH6uYNpi/OItPkr6Pg8o=
